# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzytext_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FuzzyTextDialog(object):
    def setupUi(self, FuzzyTextDialog):
        FuzzyTextDialog.setObjectName("FuzzyTextDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(FuzzyTextDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layerComboBox = QtWidgets.QComboBox(FuzzyTextDialog)
        self.layerComboBox.setObjectName("layerComboBox")
        self.verticalLayout.addWidget(self.layerComboBox)
        self.comboBoxTextField = QtWidgets.QComboBox(FuzzyTextDialog)
        self.comboBoxTextField.setObjectName("comboBoxTextField")
        self.verticalLayout.addWidget(self.comboBoxTextField)
        self.horizontalLayoutValues = QtWidgets.QHBoxLayout()
        self.horizontalLayoutValues.setObjectName("horizontalLayoutValues")
        self.btnLoadValues = QtWidgets.QPushButton(FuzzyTextDialog)
        self.btnLoadValues.setObjectName("btnLoadValues")
        self.horizontalLayoutValues.addWidget(self.btnLoadValues)
        self.verticalLayout.addLayout(self.horizontalLayoutValues)
        self.tableMapping = QtWidgets.QTableWidget(FuzzyTextDialog)
        self.tableMapping.setObjectName("tableMapping")
        self.tableMapping.setColumnCount(0)
        self.tableMapping.setRowCount(0)
        self.verticalLayout.addWidget(self.tableMapping)
        self.btnShowMetadata = QtWidgets.QPushButton(FuzzyTextDialog)
        self.btnShowMetadata.setObjectName("btnShowMetadata")
        self.verticalLayout.addWidget(self.btnShowMetadata)
        self.horizontalLayoutBottom = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBottom.setObjectName("horizontalLayoutBottom")
        self.btnApply = QtWidgets.QPushButton(FuzzyTextDialog)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayoutBottom.addWidget(self.btnApply)
        self.btnClose = QtWidgets.QPushButton(FuzzyTextDialog)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayoutBottom.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayoutBottom)
        self.helpLabel = QtWidgets.QLabel(FuzzyTextDialog)
        self.helpLabel.setWordWrap(True)
        self.helpLabel.setObjectName("helpLabel")
        self.verticalLayout.addWidget(self.helpLabel)

        self.retranslateUi(FuzzyTextDialog)
        QtCore.QMetaObject.connectSlotsByName(FuzzyTextDialog)

    def retranslateUi(self, FuzzyTextDialog):
        _translate = QtCore.QCoreApplication.translate
        FuzzyTextDialog.setWindowTitle(_translate("FuzzyTextDialog", "Fuzzy Text Mapping"))
        self.btnLoadValues.setText(_translate("FuzzyTextDialog", "Charger valeurs uniques"))
        self.btnShowMetadata.setText(_translate("FuzzyTextDialog", "Voir l\'historique des transformations"))
        self.btnApply.setText(_translate("FuzzyTextDialog", "Créer attribut flou"))
        self.btnClose.setText(_translate("FuzzyTextDialog", "Fermer"))
        self.helpLabel.setText(_translate("FuzzyTextDialog", "Astuce : associez chaque valeur texte du champ sélectionné à une valeur floue comprise entre 0 et 1."))
        self.helpLabel.setStyleSheet(_translate("FuzzyTextDialog", "color: gray; font-style: italic;"))
