# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzyclass_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_FuzzyClassDialog(object):
    def setupUi(self, FuzzyClassDialog):
        FuzzyClassDialog.setObjectName("FuzzyClassDialog")
        FuzzyClassDialog.resize(274, 385)
        self.verticalLayout = QtWidgets.QVBoxLayout(FuzzyClassDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layerComboBox = QtWidgets.QComboBox(FuzzyClassDialog)
        self.layerComboBox.setObjectName("layerComboBox")
        self.verticalLayout.addWidget(self.layerComboBox)
        self.horizontalLayoutValues = QtWidgets.QHBoxLayout()
        self.horizontalLayoutValues.setObjectName("horizontalLayoutValues")
        self.btnLoadValues = QtWidgets.QPushButton(FuzzyClassDialog)
        self.btnLoadValues.setObjectName("btnLoadValues")
        self.horizontalLayoutValues.addWidget(self.btnLoadValues)
        self.verticalLayout.addLayout(self.horizontalLayoutValues)
        self.tableMapping = QtWidgets.QTableWidget(FuzzyClassDialog)
        self.tableMapping.setObjectName("tableMapping")
        self.tableMapping.setColumnCount(0)
        self.tableMapping.setRowCount(0)
        self.verticalLayout.addWidget(self.tableMapping)
        self.btnShowMetadata = QtWidgets.QPushButton(FuzzyClassDialog)
        self.btnShowMetadata.setObjectName("btnShowMetadata")
        self.horizontalLayoutBottom = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBottom.setObjectName("horizontalLayoutBottom")
        self.btnApply = QtWidgets.QPushButton(FuzzyClassDialog)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayoutBottom.addWidget(self.btnApply)
        self.btnClose = QtWidgets.QPushButton(FuzzyClassDialog)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayoutBottom.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayoutBottom)
        self.helpLabel = QtWidgets.QLabel(FuzzyClassDialog)
        self.helpLabel.setWordWrap(True)
        self.helpLabel.setObjectName("helpLabel")
        self.verticalLayout.addWidget(self.helpLabel)

        self.retranslateUi(FuzzyClassDialog)
        QtCore.QMetaObject.connectSlotsByName(FuzzyClassDialog)

    def retranslateUi(self, FuzzyClassDialog):
        _translate = QtCore.QCoreApplication.translate
        FuzzyClassDialog.setWindowTitle(_translate("FuzzyClassDialog", "Fuzzy Classes Mapping"))
        self.btnLoadValues.setText(_translate("FuzzyClassDialog", "Charger valeurs uniques"))
        self.btnShowMetadata.setText(_translate("FuzzyClassDialog", "Voir l\'historique des transformations"))
        self.btnApply.setText(_translate("FuzzyClassDialog", "Reclasser le raster"))
        self.btnClose.setText(_translate("FuzzyClassDialog", "Fermer"))
        self.helpLabel.setStyleSheet(_translate("FuzzyClassDialog", "color: gray; font-style: italic;"))
        self.helpLabel.setText(_translate("FuzzyClassDialog", "Astuce : associez chaque valeur texte du champ sélectionné à une valeur floue comprise entre 0 et 1."))
