# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzyattributes_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FuzzyAttributesDialog(object):
    def setupUi(self, FuzzyAttributesDialog):
        FuzzyAttributesDialog.setObjectName("FuzzyAttributesDialog")
        FuzzyAttributesDialog.resize(320, 285)
        self.verticalLayout = QtWidgets.QVBoxLayout(FuzzyAttributesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layerComboBox = QtWidgets.QComboBox(FuzzyAttributesDialog)
        self.layerComboBox.setObjectName("layerComboBox")
        self.verticalLayout.addWidget(self.layerComboBox)
        self.fieldWithStatsLayout = QtWidgets.QHBoxLayout()
        self.fieldWithStatsLayout.setObjectName("fieldWithStatsLayout")
        self.fieldComboBox = QtWidgets.QComboBox(FuzzyAttributesDialog)
        self.fieldComboBox.setObjectName("fieldComboBox")
        self.fieldWithStatsLayout.addWidget(self.fieldComboBox)
        self.btnShowStats = QtWidgets.QPushButton(FuzzyAttributesDialog)
        self.btnShowStats.setObjectName("btnShowStats")
        self.fieldWithStatsLayout.addWidget(self.btnShowStats)
        self.verticalLayout.addLayout(self.fieldWithStatsLayout)
        self.horizontalLayoutFunction = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFunction.setObjectName("horizontalLayoutFunction")
        self.fuzzyTypeComboBox = QtWidgets.QComboBox(FuzzyAttributesDialog)
        self.fuzzyTypeComboBox.setObjectName("fuzzyTypeComboBox")
        self.horizontalLayoutFunction.addWidget(self.fuzzyTypeComboBox)
        self.labelFunctionPreview = QtWidgets.QLabel(FuzzyAttributesDialog)
        self.labelFunctionPreview.setMinimumSize(QtCore.QSize(100, 100))
        self.labelFunctionPreview.setScaledContents(True)
        self.labelFunctionPreview.setObjectName("labelFunctionPreview")
        self.horizontalLayoutFunction.addWidget(self.labelFunctionPreview)
        self.verticalLayout.addLayout(self.horizontalLayoutFunction)
        self.paramLayout = QtWidgets.QHBoxLayout()
        self.paramLayout.setObjectName("paramLayout")
        self.paramLineEdit = QtWidgets.QLineEdit(FuzzyAttributesDialog)
        self.paramLineEdit.setObjectName("paramLineEdit")
        self.paramLayout.addWidget(self.paramLineEdit)
        self.helpButton = QtWidgets.QToolButton(FuzzyAttributesDialog)
        self.helpButton.setObjectName("helpButton")
        self.paramLayout.addWidget(self.helpButton)
        self.verticalLayout.addLayout(self.paramLayout)
        self.paramExampleLabel = QtWidgets.QLabel(FuzzyAttributesDialog)
        self.paramExampleLabel.setStyleSheet("color: gray;")
        self.paramExampleLabel.setObjectName("paramExampleLabel")
        self.verticalLayout.addWidget(self.paramExampleLabel)
        self.btnShowMetadata = QtWidgets.QPushButton(FuzzyAttributesDialog)
        self.btnShowMetadata.setObjectName("btnShowMetadata")
        self.verticalLayout.addWidget(self.btnShowMetadata)
        self.buttonBox = QtWidgets.QDialogButtonBox(FuzzyAttributesDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FuzzyAttributesDialog)
        QtCore.QMetaObject.connectSlotsByName(FuzzyAttributesDialog)

    def retranslateUi(self, FuzzyAttributesDialog):
        _translate = QtCore.QCoreApplication.translate
        FuzzyAttributesDialog.setWindowTitle(_translate("FuzzyAttributesDialog", "Transformation floue d\'attributs"))
        self.btnShowStats.setText(_translate("FuzzyAttributesDialog", "Statistiques"))
        self.btnShowStats.setToolTip(_translate("FuzzyAttributesDialog", "Afficher les statistiques du champ"))
        self.paramLineEdit.setPlaceholderText(_translate("FuzzyAttributesDialog", "Paramètres séparés par des virgules"))
        self.helpButton.setToolTip(_translate("FuzzyAttributesDialog", "Afficher l’aide sur les fonctions floues"))
        self.helpButton.setText(_translate("FuzzyAttributesDialog", "?"))
        self.paramExampleLabel.setText(_translate("FuzzyAttributesDialog", "Exemple : "))
        self.btnShowMetadata.setText(_translate("FuzzyAttributesDialog", "Voir l\'historique des transformations"))
