# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzyaggregate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FuzzyAggregateDialog(object):
    def setupUi(self, FuzzyAggregateDialog):
        FuzzyAggregateDialog.setObjectName("FuzzyAggregateDialog")
        FuzzyAggregateDialog.resize(461, 361)
        self.verticalLayout = QtWidgets.QVBoxLayout(FuzzyAggregateDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLayer1 = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.labelLayer1.setMinimumSize(QtCore.QSize(10, 10))
        self.labelLayer1.setObjectName("labelLayer1")
        self.verticalLayout.addWidget(self.labelLayer1)
        self.layerCombo1 = QtWidgets.QComboBox(FuzzyAggregateDialog)
        self.layerCombo1.setObjectName("layerCombo1")
        self.verticalLayout.addWidget(self.layerCombo1)
        self.labelField1 = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.labelField1.setObjectName("labelField1")
        self.verticalLayout.addWidget(self.labelField1)
        self.fieldCombo1 = QtWidgets.QComboBox(FuzzyAggregateDialog)
        self.fieldCombo1.setObjectName("fieldCombo1")
        self.verticalLayout.addWidget(self.fieldCombo1)
        self.labelLayer2 = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.labelLayer2.setObjectName("labelLayer2")
        self.verticalLayout.addWidget(self.labelLayer2)
        self.layerCombo2 = QtWidgets.QComboBox(FuzzyAggregateDialog)
        self.layerCombo2.setObjectName("layerCombo2")
        self.verticalLayout.addWidget(self.layerCombo2)
        self.labelField2 = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.labelField2.setObjectName("labelField2")
        self.verticalLayout.addWidget(self.labelField2)
        self.fieldCombo2 = QtWidgets.QComboBox(FuzzyAggregateDialog)
        self.fieldCombo2.setObjectName("fieldCombo2")
        self.verticalLayout.addWidget(self.fieldCombo2)
        self.labelOperation = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.labelOperation.setObjectName("labelOperation")
        self.verticalLayout.addWidget(self.labelOperation)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.radioIntersection = QtWidgets.QRadioButton(FuzzyAggregateDialog)
        self.radioIntersection.setChecked(True)
        self.radioIntersection.setObjectName("radioIntersection")
        self.hboxlayout.addWidget(self.radioIntersection)
        self.radioUnion = QtWidgets.QRadioButton(FuzzyAggregateDialog)
        self.radioUnion.setObjectName("radioUnion")
        self.hboxlayout.addWidget(self.radioUnion)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.labelOutput = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.labelOutput.setObjectName("labelOutput")
        self.verticalLayout.addWidget(self.labelOutput)
        self.outputLayerName = QtWidgets.QLineEdit(FuzzyAggregateDialog)
        self.outputLayerName.setObjectName("outputLayerName")
        self.verticalLayout.addWidget(self.outputLayerName)
        self.btnShowMetadata = QtWidgets.QPushButton(FuzzyAggregateDialog)
        self.btnShowMetadata.setObjectName("btnShowMetadata")
        self.verticalLayout.addWidget(self.btnShowMetadata)
        self.defineFunctionButton = QtWidgets.QPushButton(FuzzyAggregateDialog)
        self.defineFunctionButton.setObjectName("defineFunctionButton")
        self.verticalLayout.addWidget(self.defineFunctionButton)
        self.functionLabel = QtWidgets.QLabel(FuzzyAggregateDialog)
        self.functionLabel.setObjectName("functionLabel")
        self.verticalLayout.addWidget(self.functionLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(FuzzyAggregateDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FuzzyAggregateDialog)
        QtCore.QMetaObject.connectSlotsByName(FuzzyAggregateDialog)

    def retranslateUi(self, FuzzyAggregateDialog):
        _translate = QtCore.QCoreApplication.translate
        FuzzyAggregateDialog.setWindowTitle(_translate("FuzzyAggregateDialog", "Fuzzy Aggregate"))
        self.labelLayer1.setText(_translate("FuzzyAggregateDialog", "Couche 1"))
        self.labelField1.setText(_translate("FuzzyAggregateDialog", "Champ flou 1"))
        self.labelLayer2.setText(_translate("FuzzyAggregateDialog", "Couche 2"))
        self.labelField2.setText(_translate("FuzzyAggregateDialog", "Champ flou 2"))
        self.labelOperation.setText(_translate("FuzzyAggregateDialog", "Type d’opération spatiale"))
        self.radioIntersection.setText(_translate("FuzzyAggregateDialog", "Intersection"))
        self.radioUnion.setText(_translate("FuzzyAggregateDialog", "Union"))
        self.labelOutput.setText(_translate("FuzzyAggregateDialog", "Nom de la couche résultat (ajout de _agg à la fin automatique)"))
        self.btnShowMetadata.setText(_translate("FuzzyAggregateDialog", "Voir l\'historique des transformations"))
        self.defineFunctionButton.setText(_translate("FuzzyAggregateDialog", "Définir la fonction"))
        self.functionLabel.setText(_translate("FuzzyAggregateDialog", "Code : "))
